data:
    name: 'coco'
    truncate: null
    labels: null
    
    preprocessing:
        resize: [240, 320]

    augmentation:
        photometric:
            enable: false
            primitives: 'all'
            params: {}
            random_order: true
        homograhic:
            enable: false
            params: {}
            valid_border_margin: 0
    warped_pair:
            enable: false
            params: {}
            valid_border_margin: 0

model:
    input_shape: [240, 320, 1]
    batch_size: 1
    threshold: 0.015
    nms_size: 4
    # top_k: 300
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        valid_border_margin: 3
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.85

path:
    coco_path: "/data/Datasets/COCO2014"
    ckpt_path: "/data/Models/MagicPoint/2022_08_26-03_32/weights.h5"
    output_path: "/data/Datasets/COCO_MagicPoint"