data:
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1} # draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1

    preprocessing:
        blur_size: 21
        resize: [120, 160]  # Should be multiples of 8

    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 75}
                random_contrast: {strength_range: [0.3, 1.8]}
                additive_gaussian_noise: {stddev_range: [0, 15]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [50, 100]
                motion_blur: {max_kernel_size: 7}

        homographic:
            enable: true
            params:
                allow_artifacts: true
                max_angle: 1.57  # 3.14
                patch_ratio: 0.8
                perspective: true
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                rotation: true
                scaling: true
                scaling_amplitude: 0.2
                translation: true
                translation_overflow: 0.05
            valid_border_margin: 2

model:
    input_shape: [120, 160, 1]
    threshold : 0.1
    nms_size: 2

path:
    coco_path: "/data/Datasets/COCO2014"
    ckpt_path: "/data/Models/MagicPoint/2022_08_24-08_25/weights.h5"
    data_path: "/data/Datasets/synthetic_shapes/synthetic_shapes_v0/test"