path:
    train_txt_path: "/data/Datasets/VOCdevkit/VOC2012/detection-test/train.txt"
    valid_txt_path: "/data/Datasets/VOCdevkit/VOC2012/detection-test/valid.txt"
    label_path: "/data/Datasets/VOCdevkit/VOC2012/detection-test/Labels/labels.txt"
    save_path: "/data/Models/centernet"
    model_path: null ## "/data/Models/centernet/unfreeze.h5"

train:
    input_shape: [512, 512]
    backbone: "mobilenet"
    max_detection: 100
    threshold: 0.4

    freeze_train: false
    freeze_epoch: 300
    freeze_batch_size: 64

    unfreeze_epoch: 1000
    unfreeze_batch_size: 16

    init_lr: 0.00001
    max_lr: 0.001
    optimizer: "adam"
    momentum: 0.9
    weight_decay: 0.000001

export:
    ckpt_path: "/data/Models/centernet/unfreeze_split_output.h5"
    representative_data_path: "/data/Datasets/VOCdevkit/VOC2012/JPEGImages"
    saved_model_path: "/data/Models/centernet/saved_model"
    tflite_file_name: "CenterNet.tflite"
