path:
    train_txt_path: "/data/Datasets/SPC/full-name14/train.txt"
    valid_txt_path: "/data/Datasets/SPC/full-name14/valid.txt"
    label_path: "/data/Datasets/SPC/Labels/labels.txt"
    save_path: "/data/Models/CenterNet"
    ckpt_name: "SPC-CenterNet-ResNet101.h5"
    ckpt_path: null
    representative_data_path: null

train:
    input_shape: [384, 384]
    backbone: "resnet101"
    epoch: 300
    batch_size: 16
    threshold: 0.4
    max_detection: 10
    optimizer: "sgd"
    momentum: 0.9
    weight_decay: 0.0005
    imagenet_weight: null

    init_lr: 0.01
    warmup_steps: 5