data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 100
    
    truncate: null
    labels: null
    preprocessing:
        resize: [240, 320]

    augmentation:
        photometric:
            enable: false
            primitives: 'all'
            params: {}
            random_order: true
        homograhic:
            enable: false
            params: {}
            valid_border_margin: 0
    warped_pair:
            enable: false
            params: {}
            valid_border_margin: 0

model:
    input_shape: [240, 320, 1]
    batch_size: 1
    learning_rate: 0.001
    threshold: 0.001  # 0.001
    nms_size: 4
    top_k: 100
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 2
        valid_border_margin: 3
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.22
            perspective_amplitude_y: 0.22
            allow_artifacts: true
            translation_overflow: 0.1
            allow_artifacts: true

path:
    output_path: "/home/ubuntu/Datasets/COCO_MagicPoint"
    coco_path: "/home/ubuntu/Datasets/COCO2014"
    ckpt_path: "/home/ubuntu/Models/MagicPoint/ckpt.h5"